feat: redesign profile
sigle/sigle pull request #590
Opened 2022-07-11 11:06 UTC by gregogun

* Adds **stories** tab to profile page
* Adds copyable stx address to bio
* Adds username tag next to display name
* Updates visual layout of writer info

Closes #566 #583

2022-07-11 11:11 UTC, gregogun commented on sigle/src/ui/IconButton.ts
> +    cursor: 'not-allowed',
with pointerEvents set to to none, the tooltip message 'Copied!' fails to show once the copy button is clicked

2022-07-11 16:19 UTC, pradel requested changes

2022-07-11 16:19 UTC, pradel commented on .changeset/seven-shrimps-design.md
> +'@sigle/app': patch
this can be minor

2022-07-11 16:19 UTC, pradel commented on sigle/src/modules/publicHome/components/PublicHome.tsx
> +                {abbreviateAddress(userInfo.address)}
I think this link should be clickable and open a new tab showing the address in the stacks explorer, wdyt?

2022-07-11 16:19 UTC, pradel commented on sigle/src/modules/publicHome/components/PublicHome.tsx
> +                css={{
as this css is being shared among all the items in this row, maybe it make sense to create a styled component at the beginning of this file?

2022-07-11 16:19 UTC, pradel commented on sigle/src/modules/publicHome/components/PublicHome.tsx
> +  const handleClick = () => {
Let's rename this one to smth like handleCopyAddress ?

2022-07-12 12:15 UTC, pradel approved these changes

2022-07-12 12:15 UTC, merged