feat: make profile page responsive
sigle/sigle pull request #722
Opened 2022-10-18 08:24 UTC by gregogun

Closes #715

2022-10-18 09:17 UTC, pradel requested changes
@gregogun this is what I see when trying out this pr, it doesn't feel right 😅 
![Screenshot 2022-10-18 at 11 15 58](https://user-images.githubusercontent.com/5749437/196389666-d74fbc38-6271-4a7a-a596-60c1088ce9b3.png)

2022-10-18 09:34 UTC, gregogun commented
> @gregogun this is what I see when trying out this pr, it doesn't feel right 😅 ![Screenshot 2022-10-18 at 11 15 58](https://user-images.githubusercontent.com/5749437/196389666-d74fbc38-6271-4a7a-a596-60c1088ce9b3.png)

hmm this is strange indeed 😅 do you know what the screen size/width is? 

not sure what happened to the padding as it's fine for me 🤔

2022-10-19 11:15 UTC, pradel commented on sigle/src/modules/layout/components/DashboardLayout.tsx
> +  px: 0,
@gregogun issue is that by removing the padding of the main container, you are impacting all the screens depending on the dashboard layout

![Screenshot 2022-10-19 at 13 14 29](https://user-images.githubusercontent.com/5749437/196676102-21cf19c5-25ba-41a1-bf66-d7a084d5b780.png)

2022-10-19 12:42 UTC, pradel approved these changes

2022-10-19 12:42 UTC, merged